version: "2"
services:
    app:
        build: .
        image: myapp
        ports: 
            - 8090:80
        # volumes:
        #     - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: testDB
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        ports: 
            - 3306:3306
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - mysqldb:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        links: 
            - db:db
        ports:
            - 8080:80
        networks:
            - default
volumes:
    mysqldb: